// AUTO-GENERATED by scripts/generate-static-routes.mjs — do not hand-edit.
// Regenerated automatically by the "prebuild"/"predev" npm scripts before
// every build and dev server start (see package.json), so this list tracks
// src/app's actual page.tsx files instead of drifting like the old
// hand-maintained sitemap.ts array did. Run
// `npm run generate:sitemap-routes` to refresh it manually.
//
// Excludes: authenticated/private app surfaces, /admin, /api, dev-only test
// pages (mirrors robots.ts's disallow list), Next.js dynamic route segments
// (e.g. blog/[slug], exam/[id] — the Firestore-backed blog posts are added
// separately in sitemap.ts), and the Stripe post-checkout redirect pages
// (/pricing/cancel, /pricing/success — client-only, no metadata, not
// evergreen content, never in the old hand-maintained list either).

export interface StaticSitemapRoute {
  path: string;
  changeFrequency: "always" | "hourly" | "daily" | "weekly" | "monthly" | "yearly" | "never";
  priority: number;
}

export const STATIC_SITEMAP_ROUTES: StaticSitemapRoute[] = [
  { path: "/", changeFrequency: "weekly", priority: 1 },
  { path: "/about", changeFrequency: "monthly", priority: 0.7 },
  { path: "/ai-exam-generator-lebanon", changeFrequency: "monthly", priority: 0.8 },
  { path: "/bac-francais-exam-generator", changeFrequency: "monthly", priority: 0.8 },
  { path: "/blog", changeFrequency: "weekly", priority: 0.8 },
  { path: "/blog/exam-standardization", changeFrequency: "monthly", priority: 0.7 },
  { path: "/blog/generate-bac-francais-devoir", changeFrequency: "monthly", priority: 0.7 },
  { path: "/blog/generate-bac-libanais-chemistry", changeFrequency: "monthly", priority: 0.7 },
  { path: "/blog/guide-for-parents", changeFrequency: "monthly", priority: 0.7 },
  { path: "/blog/ib-mark-scheme-generator", changeFrequency: "monthly", priority: 0.7 },
  { path: "/blog/lebanese-teachers-ai-exam-generator", changeFrequency: "monthly", priority: 0.7 },
  { path: "/blog/save-time-teaching", changeFrequency: "monthly", priority: 0.7 },
  { path: "/blog/stop-recycled-exams", changeFrequency: "monthly", priority: 0.7 },
  { path: "/blog/university-assessment-ai", changeFrequency: "monthly", priority: 0.7 },
  { path: "/contact", changeFrequency: "monthly", priority: 0.5 },
  { path: "/generateur-examen-bac-libanais", changeFrequency: "monthly", priority: 0.8 },
  { path: "/ib-exam-generator", changeFrequency: "monthly", priority: 0.8 },
  { path: "/pricing", changeFrequency: "monthly", priority: 0.8 },
  { path: "/privacy", changeFrequency: "yearly", priority: 0.3 },
  { path: "/terms", changeFrequency: "yearly", priority: 0.3 },
  { path: "/upgrade", changeFrequency: "monthly", priority: 0.8 },
];
